
import Head from 'next/head'
import { Navbar } from './Navbar'

interface WrapperProps {
    children: React.ReactNode;
}

export const Title: string = "Auth Next App"

export const Layout = ({ children }: WrapperProps) => {
    return (
        <>
            <Head>
                <title>{Title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="min-h-screen bg-gray-100">
                <Navbar />
                <main className='container flex h-[85vh] flex-col justify-center items-center m-auto'>{/* mx-auto my-8 */}
                    {children}
                </main>
            </div>
        </>
    )
}
